added multiple sheets feature (#10)
* added multiple sheets feature

* Fix `TypeError: get_sheet_name() missing 1 required positional argument: 'stream_config'`

* Fix lint issues

* Add test environment to `meltano.yml`

* Specify `key_properties` setting in `meltano.yml`

* Specify `array` kind for `sheets` setting in `meltano.yml`

---------

Co-authored-by: Reuben Frankel <rfrankel@matatika.com>